name: ðŸ¤– CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  KOTLIN_MAIN_KTS_COMPILED_SCRIPTS_CACHE_DIR: ${{ github.workspace }}/.main.kts

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: 24
          distribution: temurin

      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: ðŸ’¾ Cache Kotlin scripts
        uses: actions/cache@v4
        with:
          path: ${{ env.KOTLIN_MAIN_KTS_COMPILED_SCRIPTS_CACHE_DIR }}
          key: kts-${{ runner.os }}-${{ hashFiles('**/*.main.kts') }}
      - run: mkdir -p "$KOTLIN_MAIN_KTS_COMPILED_SCRIPTS_CACHE_DIR"

      - name: ðŸ”£ Fetching inputsâ€¦
        run: ./inputs.main.kts
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}

      - run: ./gradlew build

      - name: ðŸ“¦ Archive JUnit HTML report
        uses: actions/upload-artifact@v5
        with:
          name: junit-html
          path: build/reports/tests/test

      - name: ðŸ“¦ Archive JUnit XML report
        uses: actions/upload-artifact@v5
        with:
          name: junit-xml
          path: build/test-results/test/**.xml
